<?php
    session_start();

    $GLOBALS['Tlw'] = array(
        "Português" => array('Erro: ', 'Erro no envio do arquivo: ', 'Cadastrado já existe >:(', 'Sucesso', 'Erro ao cadastrar ;-;', 'Não Encontrado', 'Sucesso', 'Erro ao atualizar os dados.', 'Página inicial', 'Jujutsu RPG', 'Novo', 'Entrar', 'Link Direto', 'Créditos e Contato', 'Ficha de RPG', 'Créditos', 'Site inspirado no sistema Feiticeiros e Maldições, todos os créditos reservados aos seus criadores, e créditos reservados a Gege por sua obra em manga Jujutsu no Kaisen. Por fim, site desenvolvido pelo programador Murilo Gimenez','Método de requerimento inválido.','Novo Servidor','Código de ID do servidor:', 'Copiar', 'Você vai usar o código para você e os jogadores entrarem por aqui:', 'Criar Servidor', 'Nome do RPG', 'Nome do mestre', 'Senha', 'Confirme a senha', 'Não esqueça de repetir a senha para confirmar', 'Bem, agora é repetir a senha', 'Ótimo, só terminar de pôr a senha', 'As senhas estão diferentes, amigo', 'Agora pode focar além da senha','agora é só criar meu rei','Entre no servidor','Código','Você é o dono do servidor?','Olá amigo, Só colar abaixo o código do server!','Escreve mais do código eu não sou adivinho!!!','Ok é o server','? se for o código total é','esse server não existe!!!','Nome ou senha do Mestre estão incorretos.','Por favor, preencha todos os campos necessários.'),

        "English" =>array('Error: ', 'File upload error: ', 'Already registered >:(', 'Success', 'Registration error ;-;', 'Not Found', 'Success', 'Error updating data.', 'Home', 'Jujutsu RPG', 'New', 'Login', 'Direct Link', 'Credits and Contact', 'RPG Sheet', 'Credits', 'Site inspired by the system Sorcerers and Curses, all credits reserved to its creators, and credits reserved to Gege for his work in the manga Jujutsu Kaisen. Finally, site developed by programmer Murilo Gimenez','Invalid request method.','New Server','Server ID code:', 'Copy', 'You will use the code for you and the players to enter here:', 'Create Server', 'RPG Name', 'Master\'s Name', 'Password', 'Confirm Password', 'Don\'t forget to repeat the password to confirm', 'Well, now repeat the password', 'Great, just finish entering the password', 'The passwords are different, friend', 'Now you can focus beyond the password','Now it\'s just time to create, dude','Enter the server','Code','Are you the server owner?','Hello friend, just paste the server code below!','Write more of the code, I am not a mind reader!!!','Ok, it is the server','? if it is the total code is','this server does not exist!!!','Master name or password are incorrect.','Please fill in all required fields.'),
        
        "German" => array('Fehler: ', 'Fehler beim Hochladen der Datei: ', 'Bereits registriert >:(', 'Erfolg', 'Registrierungsfehler ;-;', 'Nicht gefunden', 'Erfolg', 'Fehler beim Aktualisieren der Daten.', 'Startseite', 'Jujutsu RPG', 'Neu', 'Anmelden', 'Direktlink', 'Credits und Kontakt', 'RPG-Blatt', 'Credits', 'Website inspiriert vom System Hexer und Flüche, alle Rechte vorbehalten an die Ersteller und Gege für sein Werk im Manga Jujutsu Kaisen. Schließlich entwickelt von Programmierer Murilo Gimenez','Ungültige Anforderungsmethode.','Neuer Server','Server-ID-Code:', 'Kopieren', 'Sie werden den Code verwenden, damit Sie und die Spieler hier eintreten können:', 'Server erstellen', 'Name des RPG', 'Name des Meisters', 'Passwort', 'Passwort bestätigen', 'Vergessen Sie nicht, das Passwort zur Bestätigung zu wiederholen', 'Gut, jetzt wiederholen Sie das Passwort', 'Großartig, beenden Sie einfach die Eingabe des Passworts', 'Die Passwörter sind unterschiedlich, Freund', 'Jetzt können Sie sich über das Passwort hinaus konzentrieren','Jetzt ist es nur noch Zeit zu erstellen, mein Freund','Server betreten','Code','Sind Sie der Besitzer des Servers?','Hallo Freund, fügen Sie einfach den Servercode unten ein!','Schreiben Sie mehr vom Code, ich bin kein Gedankenleser!!!','Ok, das ist der Server','? wenn es der gesamte Code ist','dieser Server existiert nicht!!!','Mastername oder Passwort sind inkorrekt.','Bitte füllen Sie alle erforderlichen Felder aus.'),

        "Japanese" => array('エラー：', 'ファイルのアップロードエラー：', 'すでに登録されています >:(', '成功', '登録エラー ;-;', '見つかりません', '成功', 'データの更新エラー。', 'ホームページ', '呪術RPG', '新規', 'ログイン', '直接リンク', 'クレジット', 'RPGシート', 'クレジット', 'システムSorcerers and Cursesにインスパイアされたサイト、すべてのクレジットはその作成者に帰属し、ジェジェの漫画「呪術廻戦」に対するクレジット。最後に、プログラマMurilo Gimenezによって開発されたサイト','無効なリクエスト方法。','新しいサーバ','サーバIDコード：', 'コピー', 'あなたとプレイヤーがここに入るためにコードを使用します：', 'サーバを作成する', 'RPGの名前', 'マスターの名前', 'パスワード', 'パスワードを確認する', 'パスワードを確認するためにパスワードを繰り返さないでください', 'さて、今パスワードを繰り返します', '素晴らしい、パスワードの入力を終了するだけです', 'パスワードが異なる、友よ', '今はパスワードを超えて集中できます','これで作成する時間です、友よ。', 'サーバーに参加する','コード','サーバーの所有者ですか？','こんにちは、友達、下のサーバーコードを貼り付けてください！','コードをもう少し書いてください、私は占い師ではありません！','Ok、これがサーバーです','？それが合計コードである場合','このサーバーは存在しません！！！','マスターの名前またはパスワードが間違っています。','すべての必須フィールドを入力してください。'),

        "Russian" => array('Ошибка: ', 'Ошибка загрузки файла: ', 'Уже зарегистрировано >:(', 'Успех', 'Ошибка регистрации ;-;', 'Не найдено', 'Успех', 'Ошибка обновления данных.', 'Главная страница', 'Jujutsu RPG', 'Новый', 'Войти', 'Прямая ссылка', 'Кредиты', 'RPG-лист', 'Кредиты', 'Сайт, вдохновленный системой Sorcerers and Curses, все права принадлежат их создателям, и кредиты принадлежат Геге за его работу в манге Jujutsu Kaisen. Наконец, сайт разработан программистом Мурило Гименезом','Недопустимый метод запроса.','Новый сервер','Код ID сервера:', 'Копировать', 'Вы будете использовать код для входа с вами и игроками здесь:', 'Создать сервер', 'Имя RPG', 'Имя мастера', 'Пароль', 'Подтвердите пароль', 'Не забудьте повторить пароль для подтверждения', 'Хорошо, теперь повторите пароль', 'Отлично, просто закончите ввод пароля', 'Пароли разные, друг', 'Теперь вы можете сосредоточиться за пределами пароля','Теперь просто нужно создать, мой друг','Войти на сервер','Код','Вы владелец сервера?','Привет, друг, просто вставьте код сервера ниже!','Напишите больше кода, я не ясновидящий!','Ок, это сервер','? если это общий код','этот сервер не существует!!!','Имя владельца или пароль неверны.','Пожалуйста, заполните все обязательные поля.'),

    );
?>